---

- name: Creating sudoers configuration in /etc/sudoers.d/"{{ sudo_sudoers_file }}"
  ansible.builtin.template:
    src: "etc/sudoers.d/ansible.j2"
    dest: "{{ sudo_sudoers_d_path }}/{{ sudo_sudoers_file }}"
    validate: "{{ sudo_visudo }} -cf %s"
    owner: root
    group: "{{ sudo_sudoers_group }}"
    mode: "0440"

- name: "List files in {{ sudo_sudoers_d_path }}"
  ansible.builtin.find:
    paths: "{{ sudo_sudoers_d_path }}"
    patterns: "*"
  register: sudoers_contents
  changed_when: false
  when: purge_other_sudoers_files | bool

- name: "Remove unmanaged files in {{ sudo_sudoers_d_path }}"
  ansible.builtin.file:
    path: "{{ sudo_sudoers_d_path }}/{{ item.path | basename }}"
    state: absent
  loop: "{{ sudoers_contents.files }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - purge_other_sudoers_files | bool
    - (item.path|basename) != sudo_sudoers_file
