---

- name: Import vars.yml
  ansible.builtin.import_tasks: vars.yml
  tags:
    - system
    - sudo
    - vars
    - sudo-vars

- name: Import install.yml
  ansible.builtin.import_tasks: install.yml
  tags:
    - system
    - sudo
    - install
    - sudo-install

- name: Import config.yml
  ansible.builtin.import_tasks: config.yml
  tags:
    - system
    - sudo
    - config
    - sudo-config
